# Generated by Django 5.0.2 on 2024-02-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='Untitled', max_length=20),
        ),
    ]
