# Generated by Django 5.0.2 on 2024-02-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0002_project_description_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
